language: java
jdk:
  - openjdk11

branches:
  only:
    - master
    # Travis CI Server
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - mkdir -p deploy # Travis 실행 위치에서 zip에 포함시킬 파일들을 담을 디렉토리 생성
  - zip -r server-side-repo *
  - mv server-side-repo.zip deploy/server-side-repo.zip # deploy로 zip파일 이동

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: handup-travis-deploy # S3 버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip 파일 접근을 private으로
    local_dir: deploy # before_deploy에서 생성한 디렉토리
    wait_until_deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: handup-travis-deploy
    key: server-side-repo.zip

    bundle_type: zip
    application: springboot-webservice
    deployment_group: springboot-webservice-group
    region: ap-northeast-2
    wait_until_deployed: true

# CI Complete Send Mail
notifications:
  email:
    recipients:
      - plzsenddm@gmail.com