language: java
jdk:
  - openjdk8
  - openjdk11

branches:
  only:
    - develop-1
    # Travis CI Server
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

# CI Complete Send Mail
notifications:
  email:
    recipients:
      - plzsenddm@gamil.com

