#cloud:
#  aws:
#    credentials:
#      accessKey: AKIA2DJLTH7P74FE3F6Q
#      secretKey: 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
#    s3:
#      bucket: handup-img-bucket
#    region:
#      static: ap-northeast-2
#    stack:
#      auto: false
