server:
  port: 8081
spring:
  datasource:
    # driver-class-name: com.mysql.cj.jdbc.Driver
    # url: jdbc:mysql://localhost:3306/auth?characterEncoding=UTF-8&serverTimezone=UTC

    url: jdbc:h2:tcp://localhost/~/test
    driver-class-name: org.h2.Driver
    username: sa
    password:

  security:
    user:
      name: user
      password: test

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
    # database-platform: org.hibernate.dialect.MySQL8Dialect

  messages:
    basename: i18n/exception
    encoding: UTF-8


  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true


logging:
  level:
    org.hibernate.SQL: debug
    #org.hibernate.type: trace